"""
LOD2 CityJSON exporter for irregular (wharf cellar) rooms without additional shape simplification.

This version implements the bottom-up approach you requested:
  - Uses your ordered floor hull points exactly (no alpha/convex simplification).
  - Scans the rest of the pointcloud to find points that lie close to each floor vertex
    and close to each floor edge (within a small tolerance) to capture arched ceilings,
    intermediate changes in wall height, and irregular top-edges.
  - Subdivides edges where intermediate roof points exist so wall polygons follow the
    actual measured roof/ceiling profile.
  - Triangulates the roof using all top points (vertex tops + interior roof samples) so
    vaulted/arched ceilings are represented in LOD2.
  - Assembles a CityJSON `Solid` where:
      * floor face = ordered floor ring at flat floor_z
      * roof faces = triangles from triangulation (each triangle is a surface)
      * walls = polygon surfaces for each subdivided edge where the top edge follows
        the measured roof heights

Notes / parameters you can tweak:
  - xy_tol: XY tolerance when matching pointcloud samples to a floor vertex or edge.
  - samples_along_edge: when no measured intermediate points exist, we sample along
    an edge and query the nearest roof point to get a smoother top edge.

Requirements (same as before):
  pip install open3d numpy shapely scipy

"""

import json
from collections import OrderedDict
import numpy as np
from shapely.geometry import Point, Polygon, LineString
from scipy.spatial import Delaunay, cKDTree
import open3d as o3d


def order_points_ccw(points_xy):
    center = np.mean(points_xy, axis=0)
    angles = np.arctan2(points_xy[:, 1] - center[1], points_xy[:, 0] - center[0])
    order = np.argsort(angles)
    return points_xy[order]


def points_near_vertex(x, y, pts, xy_tol=0.05):
    mask = (np.abs(pts[:, 0] - x) <= xy_tol) & (np.abs(pts[:, 1] - y) <= xy_tol)
    return pts[mask]


def points_near_edge(a, b, pts, dist_tol=0.1):
    # return points whose distance to segment ab is <= dist_tol
    seg = LineString([tuple(a), tuple(b)])
    result = []
    for p in pts:
        if seg.distance(Point(p[0], p[1])) <= dist_tol:
            # compute along-segment parameter t for sorting
            proj = seg.project(Point(p[0], p[1]))
            length = seg.length
            t = proj / length if length > 0 else 0
            result.append((t, p))
    result.sort(key=lambda x: x[0])
    return [r[1] for r in result]


def sample_along_segment(a, b, n):
    a = np.asarray(a)
    b = np.asarray(b)
    ts = np.linspace(0.0, 1.0, n)
    return [tuple(a + (b - a) * t) for t in ts]


def triangulate_roof_points(points_xyzc, footprint_poly: Polygon):
    # keep only interior or on-boundary points
    inside_mask = np.array([footprint_poly.contains(Point(p[0], p[1])) or footprint_poly.touches(Point(p[0], p[1])) for p in points_xyzc])
    sample = points_xyzc[inside_mask]
    if len(sample) < 3:
        raise ValueError("Not enough roof samples inside footprint for triangulation")
    tri = Delaunay(sample[:, :2])
    verts = [tuple(p) for p in sample.tolist()]
    faces = [tuple(tri.simplices[i]) for i in range(len(tri.simplices))]
    return verts, faces


def make_vertices_indexed(vertex_list):
    verts = []
    index = {}
    for v in vertex_list:
        key = (float(v[0]), float(v[1]), float(v[2]))
        if key not in index:
            index[key] = len(verts)
            verts.append([key[0], key[1], key[2]])
    return verts, index


def export_cityjson(vertices, surfaces, outpath, object_id="room_1", obj_type="Building"):
    cityjson = OrderedDict()
    cityjson["type"] = "CityJSON"
    cityjson["version"] = "1.1"
    cityjson["metadata"] = {"reference": "generated by script"}
    cityjson["CityObjects"] = {
        object_id: {
            "type": obj_type,
            "geometry": [{
                "type": "Solid",
                "lod": "2.0",
                "boundaries": [surfaces]
            }]
        }
    }
    cityjson["vertices"] = vertices
    with open(outpath, "w") as f:
        json.dump(cityjson, f, indent=2)
    print(f"Wrote CityJSON to {outpath}")


def build_lod2_from_floor_and_pointcloud(boundary_points_xyz,
                                         pointcloud_xyz,
                                         floor_z=None,
                                         xy_tol=0.05,
                                         edge_dist_tol=0.15,
                                         samples_along_edge=8,
                                         outpath="room_lod2_cityjson.json"):
    """Main builder.

    boundary_points_xyz: Nx3 array of your exact floor hull points in any order (we order them CCW)
    pointcloud_xyz: Mx3 array of the rest of points (roof/ceiling samples and other points)
    xy_tol: tolerance for matching roof points to a floor vertex
    edge_dist_tol: tolerance for point-to-edge distance to collect intermediate points along an edge
    samples_along_edge: how many samples to synthesize along an edge when no measured points exist
    """
    bpts = np.asarray(boundary_points_xyz)
    pts = np.asarray(pointcloud_xyz)
    if bpts.shape[1] != 3 or pts.shape[1] != 3:
        raise ValueError("Expected Nx3 arrays")

    if floor_z is None:
        floor_z = float(np.percentile(bpts[:, 2], 5))

    # order floor vertices
    ordered_xy = order_points_ccw(bpts[:, :2])
    n = len(ordered_xy)

    # Determine roof top for each floor vertex using nearby points
    top_vertices = []  # list of (x,y,z) for each floor vertex
    for (x, y) in ordered_xy:
        nearby = points_near_vertex(x, y, pts, xy_tol)
        if len(nearby) > 0:
            z_top = float(np.max(nearby[:, 2]))
        else:
            # fallback: query nearest point in whole pointcloud (KDTree)
            tree = cKDTree(pts[:, :2])
            d, idx = tree.query([ (x,y) ], k=1)
            z_top = float(pts[idx[0], 2])
        top_vertices.append((float(x), float(y), float(z_top)))

    # Build roof sample set: include the top_vertices and interior roof points from pointcloud
    roof_candidates = []
    for v in top_vertices:
        roof_candidates.append(v)

    # include interior roof samples (points whose XY lie inside the footprint polygon)
    footprint_poly = Polygon([tuple(p) for p in ordered_xy])
    for p in pts:
        if footprint_poly.contains(Point(p[0], p[1])) or footprint_poly.touches(Point(p[0], p[1])):
            roof_candidates.append((float(p[0]), float(p[1]), float(p[2])))
    roof_candidates = np.array(roof_candidates)

    # Triangulate roof
    try:
        roof_verts_local, roof_faces_local = triangulate_roof_points(roof_candidates, footprint_poly)
        # roof_verts_local are coords, roof_faces_local are indices into roof_candidates filtered list
    except Exception as e:
        print("Roof triangulation failed, falling back to flat roof:", e)
        ceil_z = float(np.percentile(roof_candidates[:, 2], 95)) if len(roof_candidates)>0 else (max([v[2] for v in top_vertices]) if len(top_vertices)>0 else floor_z+2.5)
        roof_verts_local = [(x,y,ceil_z) for (x,y) in ordered_xy]
        roof_faces_local = [[i for i in range(len(roof_verts_local))]]

    # For walls: for each edge, find measured points near the edge and create a subdivided top edge
    wall_polys = []
    for i in range(n):
        a = ordered_xy[i]
        b = ordered_xy[(i+1)%n]
        measured = points_near_edge(a, b, pts, dist_tol=edge_dist_tol)
        top_edge_pts = []
        if len(measured) >= 2:
            # Use measured points along edge (sorted by t) - pick highest z for each unique XY cluster
            # We will collapse nearly duplicate XYs by rounding
            uniq = {}
            for p in measured:
                key = (round(float(p[0]), 4), round(float(p[1]), 4))
                if key not in uniq:
                    uniq[key] = float(p[2])
                else:
                    uniq[key] = max(uniq[key], float(p[2]))
            sorted_xy = sorted(uniq.items(), key=lambda kv: (kv[0][0], kv[0][1]))
            # however we need them ordered along the segment; project t
            seg = LineString([tuple(a), tuple(b)])
            ordered_meas = []
            for (kx, ky), zval in uniq.items():
                t = seg.project(Point(kx, ky)) / (seg.length if seg.length>0 else 1)
                ordered_meas.append((t, (kx, ky, zval)))
            ordered_meas.sort(key=lambda x: x[0])
            top_edge_pts = [tuple(m[1]) for m in ordered_meas]
        else:
            # synthesize samples along the edge and query nearest roof z
            samples = sample_along_segment(a, b, samples_along_edge)
            tree = cKDTree(pts[:, :2])
            for s in samples:
                d, idx = tree.query([s], k=1)
                z = float(pts[idx[0], 2])
                top_edge_pts.append((float(s[0]), float(s[1]), z))
        # Now build the wall polygon (lower edge floor_z from a->b, upper edge top_edge_pts from b->a)
        lower = [(float(s[0]), float(s[1]), float(floor_z)) for s in [*sample_along_segment(a,b, max(2,len(top_edge_pts)))]]
        upper = list(reversed(top_edge_pts))
        poly = lower + upper
        wall_polys.append(poly)

    # Create floor polygon 3D
    floor_poly_3d = [(float(x), float(y), float(floor_z)) for (x,y) in ordered_xy]

    # Assemble all polygons: floor, each roof triangle, walls
    all_polys_coords = []
    all_polys_coords.append(floor_poly_3d)

    # roof faces: if triangulation produced simplices referencing roof_candidates indices, we need to map them
    # but our triangulate_roof_points returned faces as indices into the 'sample' array used internally.
    # For simplicity, we will reconstruct the roof triangles by performing Delaunay on roof_candidates directly now.
    try:
        # do a fresh Delaunay on roof_candidates
        rc = np.array(roof_candidates)
        tri = Delaunay(rc[:, :2])
        for simplex in tri.simplices:
            tri_coords = [tuple(rc[i]) for i in simplex]
            all_polys_coords.append(tri_coords)
    except Exception as e:
        # fallback: single roof polygon using roof verts from ordered floor tops
        roof_polygon = [(v[0], v[1], v[2]) for v in top_vertices]
        all_polys_coords.append(roof_polygon)

    # add wall polys
    for w in wall_polys:
        all_polys_coords.append(w)

    # Deduplicate vertices into global list
    flat_list = [tuple(v) for poly in all_polys_coords for v in poly]
    verts, idx_map = make_vertices_indexed(flat_list)

    # Build surfaces as index lists (each surface is a single outer ring)
    surfaces_idx = []
    for poly in all_polys_coords:
        ids = [ idx_map[tuple(v)] for v in poly ]
        surfaces_idx.append([ids])

    # One shell containing all surfaces
    shell = surfaces_idx

    export_cityjson(verts, shell, outpath)


def export_to_cityjson(point_cloud: o3d.geometry.PointCloud, 
                      floor_points: np.ndarray, 
                      roof_points: np.ndarray, 
                      output_path: str = "building.json",
                      xy_tol: float = 0.05,
                      edge_dist_tol: float = 0.15,
                      samples_per_edge: int = 12) -> None:
    """
    Export a point cloud to CityJSON format with floor, walls, and roof surfaces.
    
    Creates a LOD2 building model by generating walls from floor boundary points
    and triangulating roof points within the building footprint.

    Args:
        point_cloud (o3d.geometry.PointCloud): Combined point cloud containing building data.
        floor_points (np.ndarray): Array of floor corner points for footprint generation.
        roof_points (np.ndarray): Array of roof/ceiling points for roof surface creation.
        output_path (str, optional): Path to save the CityJSON file. Defaults to "building.json".
        xy_tol (float, optional): XY tolerance for matching roof points to floor vertices. Defaults to 0.05.
        edge_dist_tol (float, optional): Distance tolerance for point-to-edge matching. Defaults to 0.15.
        samples_per_edge (int, optional): Number of samples per wall edge. Defaults to 12.

    Example:
        >>> floor_corners = np.array([[0, 0, 0], [10, 0, 0], [10, 5, 0], [0, 5, 0]])
        >>> roof_pts = np.array([[0, 0, 3], [10, 0, 3], [10, 5, 3], [0, 5, 3]])
        >>> export_to_cityjson(combined_pcd, floor_corners, roof_pts, "my_building.json")
    """
    from temp import build_lod2_from_floor_and_pointcloud
    
    # Convert Open3D point cloud to numpy array if needed
    if hasattr(point_cloud, 'points'):
        all_points = np.asarray(point_cloud.points)
    else:
        all_points = point_cloud
    
    # Determine floor height from floor points
    floor_z = float(np.min(floor_points[:, 2]))
    
    # Export to CityJSON using the temp.py function
    build_lod2_from_floor_and_pointcloud(
        boundary_points_xyz=floor_points,
        pointcloud_xyz=roof_points,
        floor_z=floor_z,
        xy_tol=xy_tol,
        edge_dist_tol=edge_dist_tol,
        samples_along_edge=samples_per_edge,
        outpath=output_path
    )
    
    print(f"Building exported to CityJSON: {output_path}")


# If run as script, small synthetic demo
if __name__ == '__main__':
    # small test shape (irregular) + vaulted roof points
    boundary_xyz = np.array([
        [0,0,-1.2],[3,0,-1.2],[4,1.2,-1.2],[3.5,3,-1.2],[1.5,3.5,-1.2],[-0.5,2.0,-1.2]
    ])
    # create roof samples: higher in center (vault)
    xs = np.linspace(-0.5,4,25)
    ys = np.linspace(0,3.5,25)
    roof_pts = []
    for x in xs:
        for y in ys:
            r = np.sqrt((x-1.8)**2 + (y-1.5)**2)
            z = 2.5 + 1.2*np.exp(-0.6*r) + 0.03*np.random.randn()
            roof_pts.append([x,y,z])
    roof_pts = np.array(roof_pts)

    build_lod2_from_floor_and_pointcloud(boundary_xyz, roof_pts, floor_z=-1.2, xy_tol=0.05, edge_dist_tol=0.15, samples_along_edge=12, outpath='cellar_lod2_generated.json')
    print('Done. Generated cellar_lod2_generated.json')
